// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef ARMS_H
#define ARMS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/*
 * Author: 	Matthew Lynch
 * Date:	02/10/2018
 */
class Arms: public frc::Subsystem
{
	public:
		Arms();
		void InitDefaultCommand() override;
		void Periodic() override;

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

		// Functions for moving the flywheels
		void SpinWheelsForward();
		void SpinWheelsBackward();
		void StopSpinning();

		// Functions for moving the hinged plate
		void LowerArms();
		void RaiseArms();
		void StopMovingArms();

	private:
		// It's desirable that everything possible is private except
		// for methods that implement subsystem capabilities

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::SpeedController> leftArmMotor;
	std::shared_ptr<frc::SpeedController> rightArmMotor;
	std::shared_ptr<frc::SpeedController> hingeMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
};

#endif
