// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/*
 * Author: 	Matthew Lynch
 * Date:	02/10/2018
 */
class DriveTrain: public frc::Subsystem
{
	public:
		DriveTrain();
		void InitDefaultCommand() override;
		void Periodic() override;

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

		void driveLeftSide( double value = 0.0 );
		void driveRightSide( double value = 0.0 );
		void haltDriving();
		bool getDriveMethod();
		void setDriveMethod( bool dM );

	private:
		// It's desirable that everything possible is private except
		// for methods that implement subsystem capabilities

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

		std::shared_ptr<frc::SpeedController> leftDriveMotor;
		std::shared_ptr<frc::Encoder> leftDriveEncoder;
		std::shared_ptr<frc::PIDController> leftSide;
		std::shared_ptr<frc::SpeedController> rightDriveMotor;
		std::shared_ptr<frc::Encoder> rightDriveEncoder;
		std::shared_ptr<frc::PIDController> rightSide;

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

		bool driveMethod;
};

#endif
