// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"

AutonomousCommand::AutonomousCommand(): frc::Command()
{
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::driveTrain.get());
	SetTimeout( 1.3 ); // Timeout is 1.3 seconds
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize()
{
	Robot::driveTrain->haltDriving();
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute()
{
	Robot::driveTrain->driveLeftSide( 0.825 );
	Robot::driveTrain->driveRightSide( 0.825 );
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished()
{
	if ( IsTimedOut() == true )
	{
		return true;
	}
		else
	{
		return false;
	}
}

// Called once after isFinished returns true
void AutonomousCommand::End()
{
	Robot::driveTrain->haltDriving();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted()
{
	End();
}
