// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveRobot.h"
#include "Commands/EjectPowerCube.h"
#include "Commands/IntakePowerCube.h"
#include "Commands/LowerArms.h"
#include "Commands/MoveLift.h"
#include "Commands/RaiseArms.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xBox.reset(new frc::Joystick(0));
    
    logitech.reset(new frc::Joystick(1));
    
    logitechButton6.reset(new frc::JoystickButton(logitech.get(), 6));
    logitechButton6->WhileHeld(new RaiseArms());
    logitechButton4.reset(new frc::JoystickButton(logitech.get(), 4));
    logitechButton4->WhileHeld(new LowerArms());
    logitechButton3.reset(new frc::JoystickButton(logitech.get(), 3));
    logitechButton3->WhileHeld(new MoveLift());
    logitechButton2.reset(new frc::JoystickButton(logitech.get(), 2));
    logitechButton2->WhileHeld(new IntakePowerCube());
    logitechButton1.reset(new frc::JoystickButton(logitech.get(), 1));
    logitechButton1->WhileHeld(new EjectPowerCube());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Move Lift", new MoveLift());
    frc::SmartDashboard::PutData("Lower Arms", new LowerArms());
    frc::SmartDashboard::PutData("Raise Arms", new RaiseArms());
    frc::SmartDashboard::PutData("Eject Power Cube", new EjectPowerCube());
    frc::SmartDashboard::PutData("Intake Power Cube", new IntakePowerCube());
    frc::SmartDashboard::PutData("Drive Robot", new DriveRobot());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xBox->SetXChannel(1);
    xBox->SetYChannel(5);
    xBox->SetThrottleChannel(2);
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getLogitech() {
   return logitech;
}

std::shared_ptr<frc::Joystick> OI::getXBox() {
   return xBox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
