// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArcadeDrive.h"
#include "Commands/ArmsDown.h"
#include "Commands/ArmsIn.h"
#include "Commands/ArmsOut.h"
#include "Commands/ArmsUp.h"
#include "Commands/LeftSwitch?.h"
#include "Commands/LeftSwitchAuto.h"
#include "Commands/LiftDown.h"
#include "Commands/LiftUp.h"
#include "Commands/RightSwitchAuto.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xBox.reset(new frc::Joystick(1));
    
    logitech.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Lift Down", new LiftDown());
    frc::SmartDashboard::PutData("Lift Up", new LiftUp());
    frc::SmartDashboard::PutData("Arms Down", new ArmsDown());
    frc::SmartDashboard::PutData("Arms Up", new ArmsUp());
    frc::SmartDashboard::PutData("Arms Out", new ArmsOut());
    frc::SmartDashboard::PutData("Arms In", new ArmsIn());
    frc::SmartDashboard::PutData("Right Switch Auto", new RightSwitchAuto());
    frc::SmartDashboard::PutData("Left Switch Auto", new LeftSwitchAuto());
    frc::SmartDashboard::PutData("Left Switch?", new LeftSwitch?());
    frc::SmartDashboard::PutData("Arcade Drive", new ArcadeDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getLogitech() {
   return logitech;
}

std::shared_ptr<frc::Joystick> OI::getXBox() {
   return xBox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
