// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::pIDDriveSystemLeftDriveMotor;
std::shared_ptr<frc::SpeedController> RobotMap::pIDDriveSystemRightDriveMotor;
std::shared_ptr<frc::RobotDrive> RobotMap::pIDDriveSystemDriveSystem;
std::shared_ptr<frc::Encoder> RobotMap::pIDDriveSystemLeftDriveEncoder;
std::shared_ptr<frc::Encoder> RobotMap::pIDDriveSystemRightDriveEncoder;
std::shared_ptr<frc::AnalogInput> RobotMap::pIDDriveSystemLeftSideDistanceSensor;
std::shared_ptr<frc::AnalogInput> RobotMap::pIDDriveSystemRightSideDistanceSensor;
std::shared_ptr<frc::SpeedController> RobotMap::pIDLiftSystemLiftMotor;
std::shared_ptr<frc::AnalogInput> RobotMap::pIDLiftSystemLiftDistanceSensor;
std::shared_ptr<frc::SpeedController> RobotMap::armSystemLeftArmMotor;
std::shared_ptr<frc::SpeedController> RobotMap::armSystemRightArmMotor;
std::shared_ptr<frc::SpeedController> RobotMap::armSystemHingeMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    pIDDriveSystemLeftDriveMotor.reset(new frc::Spark(0));
    lw->AddActuator("PIDDriveSystem", "Left Drive Motor", std::static_pointer_cast<frc::Spark>(pIDDriveSystemLeftDriveMotor));
    
    pIDDriveSystemRightDriveMotor.reset(new frc::Spark(1));
    lw->AddActuator("PIDDriveSystem", "Right Drive Motor", std::static_pointer_cast<frc::Spark>(pIDDriveSystemRightDriveMotor));
    
    pIDDriveSystemDriveSystem.reset(new frc::RobotDrive(pIDDriveSystemLeftDriveMotor, pIDDriveSystemRightDriveMotor));
    
    pIDDriveSystemDriveSystem->SetSafetyEnabled(true);
        pIDDriveSystemDriveSystem->SetExpiration(0.1);
        pIDDriveSystemDriveSystem->SetSensitivity(0.5);
        pIDDriveSystemDriveSystem->SetMaxOutput(1.0);

        pIDDriveSystemDriveSystem->SetInvertedMotor(frc::RobotDrive::kRearRightMotor, true);
    pIDDriveSystemLeftDriveEncoder.reset(new frc::Encoder(0, 1, false, frc::Encoder::k4X));
    lw->AddSensor("PIDDriveSystem", "Left Drive Encoder", pIDDriveSystemLeftDriveEncoder);
    pIDDriveSystemLeftDriveEncoder->SetDistancePerPulse(1.0);
    pIDDriveSystemLeftDriveEncoder->SetPIDSourceType(frc::PIDSourceType::kRate);
    pIDDriveSystemRightDriveEncoder.reset(new frc::Encoder(2, 3, false, frc::Encoder::k4X));
    lw->AddSensor("PIDDriveSystem", "Right Drive Encoder", pIDDriveSystemRightDriveEncoder);
    pIDDriveSystemRightDriveEncoder->SetDistancePerPulse(1.0);
    pIDDriveSystemRightDriveEncoder->SetPIDSourceType(frc::PIDSourceType::kRate);
    pIDDriveSystemLeftSideDistanceSensor.reset(new frc::AnalogInput(1));
    lw->AddSensor("PIDDriveSystem", "Left Side Distance Sensor", pIDDriveSystemLeftSideDistanceSensor);
    
    pIDDriveSystemRightSideDistanceSensor.reset(new frc::AnalogInput(2));
    lw->AddSensor("PIDDriveSystem", "Right Side Distance Sensor", pIDDriveSystemRightSideDistanceSensor);
    
    pIDLiftSystemLiftMotor.reset(new frc::Spark(2));
    lw->AddActuator("PIDLiftSystem", "Lift Motor", std::static_pointer_cast<frc::Spark>(pIDLiftSystemLiftMotor));
    
    pIDLiftSystemLiftDistanceSensor.reset(new frc::AnalogInput(0));
    lw->AddSensor("PIDLiftSystem", "Lift Distance Sensor", pIDLiftSystemLiftDistanceSensor);
    
    armSystemLeftArmMotor.reset(new frc::Spark(3));
    lw->AddActuator("ArmSystem", "Left Arm Motor", std::static_pointer_cast<frc::Spark>(armSystemLeftArmMotor));
    
    armSystemRightArmMotor.reset(new frc::Spark(4));
    lw->AddActuator("ArmSystem", "Right Arm Motor", std::static_pointer_cast<frc::Spark>(armSystemRightArmMotor));
    
    armSystemHingeMotor.reset(new frc::Spark(5));
    lw->AddActuator("ArmSystem", "Hinge Motor", std::static_pointer_cast<frc::Spark>(armSystemHingeMotor));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
